$rootdir = $args[0]
Write-Host Root Dir: $rootdir

Write-Host "Cleaning up existing .pp files"
Get-ChildItem -Path $rootdir/AddUp.AnyLog.Packaging -Recurse -Filter *.pp | ForEach-Object { Remove-Item $_ }

Write-Host "Generating .pp files"
$files = Get-ChildItem -Path $rootdir/AddUp.AnyLog -Recurse -Filter *.cs -File
$files | ForEach-Object { 
    $in = (Get-Content $_.FullName).Replace('AddUp.AnyLog', '$rootnamespace$.Logging')
    $outfile = "$rootdir/AddUp.AnyLog.Packaging/" + $_.Name + ".pp"
    Set-Content $outfile -Value '// <auto-generated/>', '// AddUp.AnyLog Logging abstraction', $in
} 


# Get-ChildItem $args[0]/AddUp.AnyLog/*.pp -Recurse | ForEach-Object { Remove-Item $_ }
#
#$files = Get-ChildItem -Path $args[0]/AddUp.AnyLog -Recurse -Filter *.cs -File
#$files | ForEach-Object { 
#    $in = (Get-Content $_.FullName).Replace('AddUp.AnyLog', '$rootnamespace$.Logging');
#    Set-Content ($_.FullName + ".pp") -Value '// <auto-generated/>', '// AddUp.AnyLog Logging abstraction', $in;
#} 